-- ==========================================
-- 1. 수입명품
-- ==========================================
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1, NULL, '수입명품', 1);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (101, 1, '여성신발', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10101, 101, '구두/로퍼', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10102, 101, '운동화/스니커즈', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10103, 101, '샌들/슬리퍼', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10104, 101, '워커/부츠', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (102, 1, '남성신발', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10201, 102, '구두/로퍼', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10202, 102, '운동화/스니커즈', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10203, 102, '샌들/슬리퍼', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10204, 102, '워커/부츠', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (103, 1, '가방/핸드백', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10301, 103, '숄더백', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10302, 103, '크로스백', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10303, 103, '토트백', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10304, 103, '백팩', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10305, 103, '힙색/메신저백', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10306, 103, '파우치/클러치백', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10307, 103, '서류가방', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10308, 103, '여행가방', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (104, 1, '지갑/벨트', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10401, 104, '여성용지갑', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10402, 104, '남성용지갑', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10403, 104, '머니클립/명함/키지갑', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10404, 104, '벨트/멜빵', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (105, 1, '여성의류', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10501, 105, '자켓/코트', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10502, 105, '패딩/야상/점퍼', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10503, 105, '티셔츠/민소매/탑', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10504, 105, '니트/스웨터/가디건', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10505, 105, '블라우스/남방', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10506, 105, '바지/데님', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10507, 105, '스커트', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10508, 105, '원피스/투피스', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10509, 105, '언더웨어/수영복', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (106, 1, '남성의류', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10601, 106, '자켓/코트', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10602, 106, '패딩/야상/점퍼', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10603, 106, '티셔츠/민소매', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10604, 106, '니트/스웨터/가디건', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10605, 106, '셔츠/남방', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10606, 106, '바지/데님', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10607, 106, '정장', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10608, 106, '언더웨어/수영복', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (107, 1, '패션잡화', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10701, 107, '모자', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10702, 107, '넥타이', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10703, 107, '장갑/손수건', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10704, 107, '머플러/스카프', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10705, 107, '선글라스/안경', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (108, 1, '시계/쥬얼리', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10801, 108, '여성용시계', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10802, 108, '남성용시계', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10803, 108, '반지/목걸이/귀걸이', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10804, 108, '팔찌/발찌', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (109, 1, '유아동', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10901, 109, '영유아', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10902, 109, '여아동복', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10903, 109, '남아동복', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (110, 1, '기타 수입명품', 2);

-- ==========================================
-- 2. 패션의류
-- ==========================================
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (2, NULL, '패션의류', 1);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (201, 2, '여성의류', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (20101, 201, '티셔츠/캐쥬얼의류', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (20102, 201, '니트/스웨터/가디건', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (20103, 201, '원피스/정장', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (20104, 201, '블라우스/셔츠/남방', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (20105, 201, '조끼/베스트', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (20106, 201, '바지/팬츠/청바지', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (20107, 201, '스커트/치마', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (20108, 201, '자켓/코트', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (20109, 201, '패딩/야상/점퍼', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (20110, 201, '트레이닝복', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (20111, 201, '언더웨어/잠옷', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (20112, 201, '파티복/드레스/기타', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (202, 2, '남성의류', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (20201, 202, '티셔츠/캐쥬얼의류', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (20202, 202, '니트/스웨터/가디건', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (20203, 202, '정장', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (20204, 202, '조끼/베스트', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (20205, 202, '셔츠/남방', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (20206, 202, '바지/팬츠/청바지', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (20207, 202, '자켓/코트', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (20208, 202, '패딩/야상/점퍼', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (20209, 202, '트레이닝복', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (20210, 202, '언더웨어/잠옷', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (20211, 202, '테마의상/기타', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (203, 2, '교복/체육복/단복', 2);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (204, 2, '클로젯셰어', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (20401, 204, '상의/하의', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (20402, 204, '원피스', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (20403, 204, '아우터', 3);

-- ==========================================
-- 3. 패션잡화
-- ==========================================
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (3, NULL, '패션잡화', 1);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (301, 3, '운동화', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (30101, 301, '런닝화/워킹화', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (30102, 301, '단화/캐쥬얼화', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (30103, 301, '기타운동화/관련용품', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (302, 3, '여성신발', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (30201, 302, '가보시/웨지힐/통굽', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (30202, 302, '펌프스/하이힐', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (30203, 302, '토오픈/오픈힐', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (30204, 302, '단화/로퍼', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (30205, 302, '워커/부츠/부티', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (30206, 302, '샌들/슬리퍼', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (30207, 302, '슬링백/뮬/블로퍼', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (30208, 302, '기타여성신발/관련용품', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (303, 3, '남성신발', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (30301, 303, '단화/로퍼/구두', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (30302, 303, '워커/부츠', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (30303, 303, '샌들/슬리퍼', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (30304, 303, '기타남성신발/관련용품', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (304, 3, '가방/핸드백', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (30401, 304, '숄더백', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (30402, 304, '크로스백', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (30403, 304, '토트백', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (30404, 304, '백팩', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (30405, 304, '힙색/세컨백', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (30406, 304, '파우치/클러치백', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (30407, 304, '서류가방', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (30408, 304, '여행가방', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (30409, 304, '기타가방/관련용품', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (305, 3, '지갑/벨트', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (30501, 305, '여성용지갑', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (30502, 305, '남성용지갑', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (30503, 305, '머니클립/명함/키지갑', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (30504, 305, '벨트/멜빵', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (306, 3, '악세서리/귀금속', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (30601, 306, '반지/귀걸이', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (30602, 306, '목걸이/팬던트', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (30603, 306, '팔찌/발찌', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (30604, 306, '순금/골드바/돌반지', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (307, 3, '시계', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (30701, 307, '여성용시계', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (30702, 307, '남성용시계', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (308, 3, '선글라스/안경', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (30801, 308, '선글라스', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (30802, 308, '안경/안경테', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (309, 3, '모자', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (30901, 309, '스냅백/야구모자', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (30902, 309, '패션/방한모자', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (310, 3, '기타잡화/관련용품', 2);

-- ==========================================
-- 4. 뷰티
-- ==========================================
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (4, NULL, '뷰티', 1);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (401, 4, '스킨케어', 2);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (402, 4, '메이크업', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (40201, 402, '베이스 메이크업', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (40202, 402, '아이 메이크업', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (40203, 402, '립 메이크업', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (40204, 402, '치크/하이라이터/쉐딩', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (403, 4, '팩/클렌징/필링', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (404, 4, '헤어/바디', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (405, 4, '향수', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (406, 4, '네일케어', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (407, 4, '남성 화장품', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (408, 4, '가발/기타용품', 2);

-- ==========================================
-- 5. 출산/유아동
-- ==========================================
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (5, NULL, '출산/유아동', 1);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (501, 5, '출산/육아용품', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (50101, 501, '모유수유용품', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (50102, 501, '분유수유용품', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (50103, 501, '튼살크림/스킨케어', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (50104, 501, '임부복/수유복/언더웨어', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (50105, 501, '물티슈/기저귀', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (50106, 501, '분유/이유식', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (50107, 501, '아기띠/기저귀가방', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (50108, 501, '신생아/영유아의류', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (50109, 501, '유아로션/목욕용품', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (50110, 501, '유아건강/위생용품', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (50111, 501, '유모차/웨건', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (502, 5, '유아동안전/실내용품', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (50201, 502, '카시트', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (50202, 502, '놀이매트', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (50203, 502, '보행기/쏘서/바운서/부스터', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (503, 5, '유아동의류', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (50301, 503, '유아용의류', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (50302, 503, '아동용의류', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (50303, 503, '내의/잠옷/속옷', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (50304, 503, '패딩/자켓', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (50305, 503, '한복/소품', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (504, 5, '유아동잡화', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (50401, 504, '구두/운동화/샌들/부츠', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (50402, 504, '장화/우비/우산', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (50403, 504, '모자/장갑', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (50404, 504, '책가방/여행가방', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (505, 5, '유아동가구', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (50501, 505, '침대/매트리스', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (50502, 505, '옷장/서랍장', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (50503, 505, '책상/공부상/책장', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (50504, 505, '의자/소파/빈백', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (506, 5, '유아동교구/완구', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (50601, 506, '신생아완구', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (50602, 506, '원목교구', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (50603, 506, '음악놀이/자석교구', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (50604, 506, '전동차/핫휠', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (50605, 506, '로봇', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (50606, 506, '인형/디즈니의상', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (50607, 506, '블록/레고', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (50608, 506, '대형 완구용품', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (507, 5, '기타 유아동용품', 2);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (508, 5, '코너마켓', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (50801, 508, '공용', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (50802, 508, '남아', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (50803, 508, '여아', 3);

-- ==========================================
-- 6. 모바일/태블릿
-- ==========================================
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (6, NULL, '모바일/태블릿', 1);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (601, 6, '스마트폰', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (60101, 601, '삼성', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (60102, 601, '애플', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (60103, 601, 'LG', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (60104, 601, '기타 제조사', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (602, 6, '태블릿PC', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (60201, 602, '삼성', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (60202, 602, '애플', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (60203, 602, '기타 제조사', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (603, 6, '스마트워치/밴드', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (604, 6, '일반/피쳐폰', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (605, 6, '케이스/거치대/보호필름', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (606, 6, '배터리/충전기/케이블', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (607, 6, '메모리/젠더/리더기', 2);

-- ==========================================
-- 7. 가전제품
-- ==========================================
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (7, NULL, '가전제품', 1);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (701, 7, '냉장고', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (702, 7, 'TV', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (703, 7, '세탁기/건조기', 2);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (704, 7, '주방가전', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (70401, 704, '전기밥솥', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (70402, 704, '가스/전기레인지', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (70403, 704, '전자레인지/오븐/제빵기', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (70404, 704, '정수기/탄산수제조기', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (70405, 704, '커피기기', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (70406, 704, '살균기/세척기', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (70407, 704, '주방소형가전', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (70408, 704, '업소용주방가전', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (705, 7, '스마트홈', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (70501, 705, '인공지능 스피커', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (70502, 705, '360카메라/홈캠', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (70503, 705, '스마트 램프/플러그/스위치', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (706, 7, '영상가전', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (70601, 706, '영상플레이어', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (70602, 706, '프로젝터/스마트빔', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (70603, 706, '전자사전/PMP/DMB', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (707, 7, '음향가전', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (70701, 707, '이어폰/헤드폰', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (70702, 707, '스피커', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (70703, 707, '마이크', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (70704, 707, '음향플레이어', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (70705, 707, '오디오/홈시어터', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (70706, 707, 'LP/턴테이블', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (70707, 707, '리시버/앰프', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (70708, 707, '보이스레코더', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (708, 7, '계절가전', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (70801, 708, '공기청정기/가습기/제습기', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (70802, 708, '히터/난방/온풍기', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (70803, 708, '전기/온수매트', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (70804, 708, '에어컨', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (70805, 708, '선풍기/냉풍기', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (709, 7, '생활가전', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (70901, 709, '청소기', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (70902, 709, '비데', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (70903, 709, '안마기/안마의자', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (70904, 709, '스탠드/조명', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (70905, 709, '다리미/미싱/보풀제거기', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (70906, 709, '도어록', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (710, 7, '미용가전', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (71001, 710, '드라이기/고데기', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (71002, 710, '면도기/제모기/이발기', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (71003, 710, '구강세정기/전동칫솔', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (711, 7, '기타 가전제품', 2);

-- ==========================================
-- 8. 노트북/PC
-- ==========================================
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (8, NULL, '노트북/PC', 1);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (801, 8, '노트북/넷북', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (80101, 801, '삼성', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (80102, 801, '애플', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (80103, 801, 'LG', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (80104, 801, '기타 제조사', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (802, 8, '데스크탑/본체', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (80201, 802, '일체형PC', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (80202, 802, '브랜드PC', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (80203, 802, '조립PC', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (803, 8, '모니터', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (804, 8, 'CPU/메인보드', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (805, 8, 'HDD/SSD/ODD', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (806, 8, 'RAM/VGA/SOUND', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (807, 8, 'USB/케이블', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (808, 8, '케이스/파워/쿨러', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (809, 8, '키보드/마우스/스피커', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (810, 8, '프린터/복합기/잉크/토너', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (811, 8, '공유기/랜카드', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (812, 8, '소프트웨어', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (813, 8, '기타 주변기기', 2);

-- ==========================================
-- 9. 카메라/캠코더
-- ==========================================
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (9, NULL, '카메라/캠코더', 1);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (901, 9, 'DSLR', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (902, 9, '미러리스', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (903, 9, '디지털카메라', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (904, 9, '필름/즉석카메라', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (905, 9, '캠코더/액션캠', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (906, 9, '기타 카메라', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (907, 9, '카메라렌즈', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (908, 9, '삼각대/조명/플래시', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (909, 9, '기타 악세서리', 2);

-- ==========================================
-- 10. 가구/인테리어
-- ==========================================
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (10, NULL, '가구/인테리어', 1);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1001, 10, '침실가구', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1002, 10, '침대/매트리스', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1003, 10, '서랍장/옷장', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1004, 10, '화장대/협탁/거울', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1005, 10, '거실가구', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1006, 10, '소파', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1007, 10, '거실테이블/의자', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1008, 10, '거실장/장식장', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1009, 10, '주방가구', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1010, 10, '식탁/식탁의자', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1011, 10, '렌지대/수납장', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1012, 10, '기타 주방가구', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1013, 10, '수납/선반/공간박스', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1014, 10, '학생/서재/사무용가구', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1015, 10, '기타가구', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1016, 10, '침구', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1017, 10, '커튼/카페트', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1018, 10, '조명/무드등', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1019, 10, '인테리어소품', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1020, 10, '이벤트/파티용품', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1021, 10, '디퓨저/캔들', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1022, 10, '시계/액자/팝아트', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1023, 10, '원예', 2);

-- ==========================================
-- 11. 리빙/생활
-- ==========================================
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (11, NULL, '리빙/생활', 1);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1101, 11, '주방용품', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (110101, 1101, '조리도구', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (110102, 1101, '식기/컵/텀블러', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (110103, 1101, '밀폐용기', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (110104, 1101, '주방잡화', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1102, 11, '차량용품', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (110201, 1102, '휠/타이어', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (110202, 1102, '블랙박스/네비게이션', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (110203, 1102, '카오디오/카시트', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (110204, 1102, '기타 부품/용품', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1103, 11, '식품', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1104, 11, '욕실용품', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1105, 11, '청소/세탁용품', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1106, 11, '생활잡화', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1107, 11, '기타 생활용품', 2);

-- ==========================================
-- 12. 게임
-- ==========================================
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (12, NULL, '게임', 1);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1201, 12, 'PC게임', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1202, 12, '플레이스테이션', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1203, 12, 'PSP', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1204, 12, '닌텐도', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1205, 12, 'Wii', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1206, 12, 'XBOX', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1207, 12, '게임타이틀', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1208, 12, '기타 게임', 2);

-- ==========================================
-- 13. 반려동물/취미
-- ==========================================
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (13, NULL, '반려동물/취미', 1);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1301, 13, '반려동물', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (130101, 1301, '강아지용품', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (130102, 1301, '고양이용품', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (130103, 1301, '관상어용품', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (130104, 1301, '기타 반려동물 용품', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1302, 13, '키덜트', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (130201, 1302, '피규어/브릭', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (130202, 1302, '프라모델', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (130203, 1302, '레고/조립/블록', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (130204, 1302, '무선조종/드론/헬리캠', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1303, 13, '핸드메이드/DIY', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (130301, 1303, '자수/뜨개질', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (130302, 1303, '뷰티/아로마/캔들', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (130303, 1303, '아트북/스크래치북', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (130304, 1303, 'DIY/공예', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1304, 13, '악기', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (130401, 1304, '건반악기', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (130402, 1304, '현악기', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (130403, 1304, '관악기/타악기', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1305, 13, '예술작품/골동품/수집', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1306, 13, '미술재료/미술도구', 2);

-- ==========================================
-- 14. 도서/음반/문구
-- ==========================================
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (14, NULL, '도서/음반/문구', 1);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1401, 14, '유아동도서/음반', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (140101, 1401, '0-3세', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (140102, 1401, '4-7세', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (140103, 1401, '8-9세', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (140104, 1401, '10-13세', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (140105, 1401, '그림/놀이/만화책', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (140106, 1401, '학습/전집', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (140107, 1401, '음반/DVD', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1402, 14, '학습/교육', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (140201, 1402, '학습/참고서', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (140202, 1402, '수험서/자격증', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (140203, 1402, '컴퓨터/인터넷', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (140204, 1402, '국어/외국어', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (140205, 1402, '대학교재', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (140206, 1402, '인터넷강의', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (140207, 1402, '백과사전/전집', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (140208, 1402, '기타 학습도서', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1403, 14, '소설/만화책', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (140301, 1403, '소설책', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (140302, 1403, '만화책', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1404, 14, '여행/취미/레저', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (140401, 1404, '여행/레저도서', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (140402, 1404, '취미도서', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1405, 14, '문학/과학/경영', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (140501, 1405, '문학도서', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (140502, 1405, '과학도서', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (140503, 1405, '경영도서', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1406, 14, '예술/디자인', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (140601, 1406, '잡지', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1407, 14, '기타 도서', 2);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1408, 14, '음반/DVD/굿즈', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (140801, 1408, 'CD', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (140802, 1408, 'DVD', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (140803, 1408, 'LP/기타음반', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (140804, 1408, '스타굿즈', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1409, 14, '문구/사무용품', 2);

-- ==========================================
-- 15. 티켓/쿠폰
-- ==========================================
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (15, NULL, '티켓/쿠폰', 1);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1501, 15, '티켓', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (150101, 1501, '콘서트', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (150102, 1501, '스포츠', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (150103, 1501, '뮤지컬/연극/클래식', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1502, 15, '상품권/쿠폰', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (150201, 1502, '백화점/마트/편의점', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (150202, 1502, '영화/문화/게임', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (150203, 1502, '외식/주유', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1503, 15, '여행숙박/이용권', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1504, 15, '기타 티켓/쿠폰/이용권', 2);

-- ==========================================
-- 16. 스포츠
-- ==========================================
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (16, NULL, '스포츠', 1);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1601, 16, '골프', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (160101, 1601, '드라이버', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (160102, 1601, '우드/유틸리티', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (160103, 1601, '아이언', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (160104, 1601, '웨지/퍼터', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (160105, 1601, '골프백/풀세트', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (160106, 1601, '골프의류/골프화', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (160107, 1601, '볼/용품/기타', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1602, 16, '자전거', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (160201, 1602, '하이브리드/픽시/미니벨로', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (160202, 1602, '로드바이크/사이클', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (160203, 1602, '산악자전거', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (160204, 1602, '전기자전거', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (160205, 1602, '유아/아동자전거', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (160206, 1602, '특수자전거', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (160207, 1602, '자전거용품', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (160208, 1602, '부품/부속/공구', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (160209, 1602, '악세서리/기타용품', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1603, 16, '인라인/스케이트/전동', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (160301, 1603, '인라인/스케이트용품', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (160302, 1603, '스케이트보드용품', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (160303, 1603, '전기/전동레저용품', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1604, 16, '축구', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (160401, 1604, '축구의류/축구화', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (160402, 1604, '축구공/용품', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1605, 16, '야구', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (160501, 1605, '야구의류/야구화', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (160502, 1605, '야구공/용품', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1606, 16, '농구', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (160601, 1606, '농구의류/농구화', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (160602, 1606, '농구공/용품', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1607, 16, '라켓스포츠', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (160701, 1607, '배드민턴의류/용품', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (160702, 1607, '테니스의류/용품', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (160703, 1607, '스쿼시의류/용품', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (160704, 1607, '탁구의류/용품', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1608, 16, '헬스/요가', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (160801, 1608, '헬스기구', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (160802, 1608, '헬스용품', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (160803, 1608, '요가/필라테스용품', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (160804, 1608, '보충/보조제', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1609, 16, '수상스포츠', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (160901, 1609, '비키니/여성수영복', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (160902, 1609, '남성수영복', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (160903, 1609, '웨이크바지/래쉬가드', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (160904, 1609, '아동용의류/용품', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (160905, 1609, '스쿠버/다이빙용품', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1610, 16, '겨울스포츠', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (161001, 1610, '스키/보드의류', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (161002, 1610, '스키/보드장비', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (161003, 1610, '아동용스키/보드', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1611, 16, '검도/격투/권투', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (161101, 1611, '도복', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (161102, 1611, '검도/격투/권투용품', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1612, 16, '기타 스포츠', 2);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1613, 16, '라브인증 자전거', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (161301, 1613, '로드자전거', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (161302, 1613, 'MTB/그래블', 3);

-- ==========================================
-- 17. 레저/여행
-- ==========================================
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (17, NULL, '레저/여행', 1);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1701, 17, '등산의류/용품', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (170101, 1701, '남성 등산의류', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (170102, 1701, '여성 등산의류', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (170103, 1701, '등산화/배낭/장비', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (170104, 1701, '기타 등산용품', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1702, 17, '캠핑용품', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (170201, 1702, '텐트/침낭', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (170202, 1702, '취사용품/장비', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (170203, 1702, '기타 캠핑용품', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1703, 17, '낚시용품', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1704, 17, '기타 레저/여행용품', 2);

-- ==========================================
-- 18. 중고차
-- ==========================================
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (18, NULL, '중고차', 1);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1801, 18, '국산차', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (180101, 1801, '제네시스', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (180102, 1801, '현대', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (180103, 1801, '기아', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (180104, 1801, '쉐보레(GM대우)', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (180105, 1801, '르노', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (180106, 1801, 'KGM', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (180107, 1801, '기타 국산차', 3);

INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1802, 18, '수입차', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (180201, 1802, 'BMW', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (180202, 1802, '벤츠', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (180203, 1802, '아우디', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (180204, 1802, '폭스바겐', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (180205, 1802, '미니', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (180206, 1802, '렉서스', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (180207, 1802, '도요타', 3);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (180208, 1802, '기타 수입차', 3);

-- ==========================================
-- 19. 오토바이
-- ==========================================
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (19, NULL, '오토바이', 1);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1901, 19, '125cc 이하', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1902, 19, '125cc 초과', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1903, 19, '오토바이 용품', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (1904, 19, '신차', 2);

-- ==========================================
-- 20. 공구/산업용품
-- ==========================================
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (20, NULL, '공구/산업용품', 1);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (2001, 20, '드릴/전동공구', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (2002, 20, '에어/유압', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (2003, 20, '작업공구', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (2004, 20, '측정공구', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (2005, 20, '초경/절삭/접착윤활', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (2006, 20, '전기/전자', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (2007, 20, '배관설비/포장운송', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (2008, 20, '금형공작', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (2009, 20, '용접기자재', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (2010, 20, '산업/안전/공구함', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (2011, 20, '산업자재', 2);
INSERT INTO CATEGORY (CATEGORY_NO, PARENT_NO, NAME, DEPTH) VALUES (2012, 20, '농기계/농업용공구', 2);

COMMIT;