-- QNA 테이블 컬럼 추가 (기존 테이블에 MEMBER_NO, ANSWER, ANSWERED_AT, CREATED_AT 추가)
ALTER TABLE QNA ADD (
    MEMBER_NO   NUMBER,
    ANSWER      VARCHAR2(1000),
    ANSWERED_AT TIMESTAMP,
    CREATED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- QNA 테이블에 MEMBER_NO FK 추가 (MEMBER 테이블 참조)
ALTER TABLE QNA ADD CONSTRAINT FK_QNA_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO);

COMMIT;
