--FK 제약 이름 확인 쿼리:
SELECT constraint_name, column_name
FROM user_cons_columns
WHERE table_name IN ('MEMBER', 'PRODUCT', 'AUCTION_RESULT')
AND column_name IN ('EMD_NO', 'TRADE_EMD_NO', 'DELIVERY_EMD_NO');

-- 1. MEMBER 테이블 주소 구조 변경
ALTER TABLE MEMBER DROP CONSTRAINT SYS_C0086930; -- EMD_NO FK 제약 이름 확인 후 삭제
ALTER TABLE MEMBER DROP COLUMN EMD_NO;
ALTER TABLE MEMBER ADD ADDR_ROAD  VARCHAR2(200);
ALTER TABLE MEMBER ADD ADDR_SHORT VARCHAR2(50);
-- ADDR_DETAIL 컬럼은 기존 것 그대로 유지

-- 2. PRODUCT 테이블
ALTER TABLE PRODUCT DROP COLUMN TRADE_EMD_NO;
ALTER TABLE PRODUCT ADD TRADE_ADDR_SHORT VARCHAR2(50);

-- 3. AUCTION_RESULT 테이블
ALTER TABLE AUCTION_RESULT DROP COLUMN DELIVERY_EMD_NO;
ALTER TABLE AUCTION_RESULT ADD DELIVERY_ADDR_ROAD VARCHAR2(200);
-- DELIVERY_ADDR_DETAIL 컬럼은 기존 것 그대로 유지