-- 1. 시퀀스 생성
CREATE SEQUENCE AUTO_BID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 2. 테이블 생성
CREATE TABLE AUTO_BID (
    AUTO_BID_NO  NUMBER          NOT NULL,
    MEMBER_NO    NUMBER          NOT NULL,
    PRODUCT_NO   NUMBER          NOT NULL,
    MAX_PRICE    NUMBER          NOT NULL,
    IS_ACTIVE    NUMBER(1)       DEFAULT 1 NOT NULL,
    CREATED_AT   DATE            DEFAULT SYSDATE NOT NULL,
    UPDATED_AT   DATE            DEFAULT NULL,       
    CONSTRAINT PK_AUTO_BID PRIMARY KEY (AUTO_BID_NO),
    CONSTRAINT FK_AUTO_BID_MEMBER  FOREIGN KEY (MEMBER_NO)  REFERENCES MEMBER(MEMBER_NO),
    CONSTRAINT FK_AUTO_BID_PRODUCT FOREIGN KEY (PRODUCT_NO) REFERENCES PRODUCT(PRODUCT_NO),
    CONSTRAINT CK_AUTO_BID_IS_ACTIVE CHECK (IS_ACTIVE IN (0, 1)),
    CONSTRAINT CK_AUTO_BID_MAX_PRICE CHECK (MAX_PRICE > 0)
);

-- 3. Partial Unique Index
--    IS_ACTIVE=1(활성) 인 경우에만 (MEMBER_NO, PRODUCT_NO) 조합이 유일해야 함
--    IS_ACTIVE=0(비활성) 은 여러 개 허용 (취소/초과 이력 보존)
--    Oracle: CASE WHEN으로 NULL 반환 시 unique index에서 NULL은 중복 허용됨
-- 3. Partial Unique Index (DECODE 방식으로 수정)
CREATE UNIQUE INDEX UQ_AUTO_BID_ACTIVE
    ON AUTO_BID (
        DECODE(IS_ACTIVE, 1, MEMBER_NO,  NULL),
        DECODE(IS_ACTIVE, 1, PRODUCT_NO, NULL)
    );

-- 4. 조회 성능용 일반 인덱스
CREATE INDEX IDX_AUTO_BID_PRODUCT ON AUTO_BID (PRODUCT_NO, IS_ACTIVE);
CREATE INDEX IDX_AUTO_BID_MEMBER  ON AUTO_BID (MEMBER_NO,  IS_ACTIVE);

-- 5. 코멘트
COMMENT ON TABLE  AUTO_BID                IS '자동입찰 설정 테이블';
COMMENT ON COLUMN AUTO_BID.AUTO_BID_NO    IS '자동입찰 번호 (PK)';
COMMENT ON COLUMN AUTO_BID.MEMBER_NO      IS '자동입찰 설정 회원번호 (FK → MEMBER)';
COMMENT ON COLUMN AUTO_BID.PRODUCT_NO     IS '대상 상품번호 (FK → PRODUCT)';
COMMENT ON COLUMN AUTO_BID.MAX_PRICE      IS '사용자가 설정한 입찰 상한선';
COMMENT ON COLUMN AUTO_BID.IS_ACTIVE      IS '활성여부. 1=활성, 0=비활성(취소/상한초과)';
COMMENT ON COLUMN AUTO_BID.CREATED_AT     IS '자동입찰 등록일시';
COMMENT ON COLUMN AUTO_BID.UPDATED_AT     IS '자동입찰 비활성화 처리 일시 (취소/상한초과 시 기록)';