-- ① REPORT: 둘 중 하나만 NOT NULL 강제
ALTER TABLE REPORT ADD CONSTRAINT CHK_REPORT_TARGET
  CHECK (
    (TARGET_MEMBER_NO IS NOT NULL AND TARGET_PRODUCT_NO IS NULL) OR
    (TARGET_MEMBER_NO IS NULL     AND TARGET_PRODUCT_NO IS NOT NULL)
  );

-- ② POINT_WITHDRAW: 이행 종속 컬럼 제거
ALTER TABLE POINT_WITHDRAW DROP COLUMN ADMIN_NICKNAME;

-- ③ INQUIRY: 이행 종속 컬럼 제거
ALTER TABLE INQUIRY DROP COLUMN ADMIN_NICKNAME;

-- ④ REVIEW_TAG_DEF 테이블 생성
CREATE TABLE REVIEW_TAG_DEF (
    TAG_ID          NUMBER          NOT NULL,
    TAG_NAME        VARCHAR2(50)    NOT NULL,
    APPLICABLE_ROLE VARCHAR2(10)    NOT NULL,  -- BUYER / SELLER / ALL
    CONSTRAINT PK_REVIEW_TAG_DEF PRIMARY KEY (TAG_ID)
);
CREATE SEQUENCE REVIEW_TAG_DEF_SEQ START WITH 1 INCREMENT BY 1;

-- 초기 태그 데이터 — 긍정
INSERT INTO REVIEW_TAG_DEF VALUES (REVIEW_TAG_DEF_SEQ.NEXTVAL, '응답이 빨라요',            'ALL');
INSERT INTO REVIEW_TAG_DEF VALUES (REVIEW_TAG_DEF_SEQ.NEXTVAL, '친절하고 매너가 좋아요',   'ALL');
INSERT INTO REVIEW_TAG_DEF VALUES (REVIEW_TAG_DEF_SEQ.NEXTVAL, '시간 약속을 잘 지켜요',    'ALL');
INSERT INTO REVIEW_TAG_DEF VALUES (REVIEW_TAG_DEF_SEQ.NEXTVAL, '연락이 잘 돼요',           'ALL');
INSERT INTO REVIEW_TAG_DEF VALUES (REVIEW_TAG_DEF_SEQ.NEXTVAL, '쿨거래 감사합니다',        'SELLER');
INSERT INTO REVIEW_TAG_DEF VALUES (REVIEW_TAG_DEF_SEQ.NEXTVAL, '상품 상태가 설명과 같아요','BUYER');
-- 부정
INSERT INTO REVIEW_TAG_DEF VALUES (REVIEW_TAG_DEF_SEQ.NEXTVAL, '응답이 느렸어요',              'ALL');
INSERT INTO REVIEW_TAG_DEF VALUES (REVIEW_TAG_DEF_SEQ.NEXTVAL, '불친절했어요',                 'ALL');
INSERT INTO REVIEW_TAG_DEF VALUES (REVIEW_TAG_DEF_SEQ.NEXTVAL, '약속을 지키지 않았어요',       'ALL');
INSERT INTO REVIEW_TAG_DEF VALUES (REVIEW_TAG_DEF_SEQ.NEXTVAL, '상품 상태가 설명과 달랐어요', 'BUYER');
INSERT INTO REVIEW_TAG_DEF VALUES (REVIEW_TAG_DEF_SEQ.NEXTVAL, '결제가 늦었어요',              'SELLER');
INSERT INTO REVIEW_TAG_DEF VALUES (REVIEW_TAG_DEF_SEQ.NEXTVAL, '연락이 되지 않았어요',         'SELLER');
COMMIT;

-- ⑤ REVIEW_TAG 중간 테이블 생성
CREATE TABLE REVIEW_TAG (
    REVIEW_NO   NUMBER  NOT NULL,
    TAG_ID      NUMBER  NOT NULL,
    CONSTRAINT PK_REVIEW_TAG     PRIMARY KEY (REVIEW_NO, TAG_ID),
    CONSTRAINT FK_RT_REVIEW      FOREIGN KEY (REVIEW_NO) REFERENCES REVIEW(REVIEW_NO) ON DELETE CASCADE,
    CONSTRAINT FK_RT_TAG         FOREIGN KEY (TAG_ID)    REFERENCES REVIEW_TAG_DEF(TAG_ID)
);

-- ⑥ REVIEW 테이블: WRITER_ROLE 추가, TAGS 제거
ALTER TABLE REVIEW ADD    (WRITER_ROLE VARCHAR2(10));
UPDATE REVIEW SET WRITER_ROLE = 'BUYER' WHERE WRITER_ROLE IS NULL; -- 기존 데이터 기본값
ALTER TABLE REVIEW MODIFY (WRITER_ROLE VARCHAR2(10) NOT NULL);
ALTER TABLE REVIEW DROP   COLUMN TAGS;