-- 1. RESULT_SEQ 시퀀스 존재 여부 확인
SELECT SEQUENCE_NAME FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'RESULT_SEQ';

-- 2. AUCTION_RESULT 테이블 구조 확인
SELECT COLUMN_NAME, DATA_TYPE, NULLABLE, DATA_DEFAULT
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'AUCTION_RESULT'
ORDER BY COLUMN_ID;

-- 3. BID_HISTORY의 IS_WINNER 컬럼 존재 여부
SELECT COLUMN_NAME, DATA_TYPE, NULLABLE
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'BID_HISTORY' AND COLUMN_NAME = 'IS_WINNER';

-- RESULT_SEQ가 없으면 생성
CREATE SEQUENCE RESULT_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

INSERT INTO AUCTION_RESULT (RESULT_NO, BID_NO, STATUS)
    VALUES (RESULT_SEQ.NEXTVAL, (SELECT MIN(BID_NO) FROM BID_HISTORY), '배송대기');

-- 1. PRODUCT 테이블에 WINNER_NO 컬럼이 있는지 확인 (안 나오면 이놈이 범인)
SELECT COLUMN_NAME FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'PRODUCT' AND COLUMN_NAME = 'WINNER_NO';

-- 2. BID_HISTORY 테이블에 IS_WINNER 컬럼이 있는지 확인 (안 나오면 이놈이 범인)
SELECT COLUMN_NAME FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'BID_HISTORY' AND COLUMN_NAME = 'IS_WINNER';

-- MEMBER 테이블에 탈퇴 관련 컬럼 추가
ALTER TABLE MEMBER ADD WITHDRAW_REASON  VARCHAR2(100) NULL;
ALTER TABLE MEMBER ADD WITHDRAWN_AT     DATE          NULL;
-- IS_ACTIVE = 0 으로 탈퇴 처리 (기존 컬럼 활용)

----------------------------------------------
-- 1. JPA가 몰래 만든 상품 이미지 테이블 삭제
DROP TABLE PRODUCT_IMAGE;

-- 2. 예전에 만든 통합 이미지 테이블 삭제
DROP TABLE IMAGE;

-- 3. 예전에 만든 통합 시퀀스 삭제
DROP SEQUENCE IMAGE_SEQ;

-- 상품 테이블에 찜 개수 컬럼 추가
ALTER TABLE PRODUCT ADD WISH_COUNT NUMBER DEFAULT 0 NOT NULL;

-- 상품 테이블에 배송료 컬럼 추가
ALTER TABLE PRODUCT ADD SHIPPING_FEE NUMBER DEFAULT 0 NOT NULL;

-- 1) 상품 이미지 테이블
CREATE TABLE PRODUCT_IMAGE (
    IMAGE_NO NUMBER PRIMARY KEY,             
    PRODUCT_NO NUMBER NOT NULL,              
    ORIGINAL_NAME VARCHAR2(255) NOT NULL,    
    UUID_NAME VARCHAR2(255) NOT NULL,        
    IMAGE_PATH VARCHAR2(500) NOT NULL,       
    IS_MAIN NUMBER(1) DEFAULT 0 NOT NULL,    
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL 
);

-- 2) 문의 이미지 테이블 
CREATE TABLE INQUIRY_IMAGE (
    IMAGE_NO NUMBER PRIMARY KEY,             
    INQUIRY_NO NUMBER NOT NULL,              
    ORIGINAL_NAME VARCHAR2(255) NOT NULL,    
    UUID_NAME VARCHAR2(255) NOT NULL,        
    IMAGE_PATH VARCHAR2(500) NOT NULL,       
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL 
);

-- 3) 신고 이미지 테이블 
CREATE TABLE REPORT_IMAGE (
    IMAGE_NO NUMBER PRIMARY KEY,             
    REPORT_NO NUMBER NOT NULL,               
    ORIGINAL_NAME VARCHAR2(255) NOT NULL,    
    UUID_NAME VARCHAR2(255) NOT NULL,        
    IMAGE_PATH VARCHAR2(500) NOT NULL,       
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL 
);