-- 1번부터 순서대로 실행
ALTER TABLE CHAT_ROOM ADD BUYER_LEFT  NUMBER(1) DEFAULT 0 NOT NULL;
ALTER TABLE CHAT_ROOM ADD SELLER_LEFT NUMBER(1) DEFAULT 0 NOT NULL;


-- 1. 플랫폼 수익(PLATFORM_REVENUE) 테이블 생성
CREATE TABLE PLATFORM_REVENUE (
    REVENUE_NO        NUMBER          NOT NULL,
    AMOUNT            NUMBER          NOT NULL,
    REASON            VARCHAR2(255)   NOT NULL,
    SOURCE_MEMBER_NO  NUMBER,
    RELATED_PRODUCT_NO NUMBER,
    CREATED_AT        DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_PLATFORM_REVENUE PRIMARY KEY (REVENUE_NO)
);

-- 2. 코멘트
COMMENT ON TABLE  PLATFORM_REVENUE                    IS '플랫폼(회사) 수익 내역';
COMMENT ON COLUMN PLATFORM_REVENUE.REVENUE_NO         IS '수익 식별 번호 (PK)';
COMMENT ON COLUMN PLATFORM_REVENUE.AMOUNT             IS '수익 금액 (차감된 위약금 등)';
COMMENT ON COLUMN PLATFORM_REVENUE.REASON             IS '수익 발생 사유 (예: 입찰 취소 위약금)';
COMMENT ON COLUMN PLATFORM_REVENUE.SOURCE_MEMBER_NO   IS '수익을 제공한 회원 번호 (FK-선택)';
COMMENT ON COLUMN PLATFORM_REVENUE.RELATED_PRODUCT_NO IS '관련 상품 번호 (FK-선택)';
COMMENT ON COLUMN PLATFORM_REVENUE.CREATED_AT         IS '수익 발생 일시';

-- 3. 시퀀스 생성 (프로젝트 컨벤션: 테이블명_SEQ)
CREATE SEQUENCE PLATFORM_REVENUE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;


-- 배송비 db삭제
ALTER TABLE PRODUCT DROP COLUMN SHIPPING_FEE;