-- 1. 계좌 테이블
CREATE TABLE BANK_ACCOUNT (
    ACCOUNT_NO      NUMBER          NOT NULL,
    MEMBER_NO       NUMBER          NOT NULL,
    BANK_NAME       VARCHAR2(30)    NOT NULL,
    ACCOUNT_NUMBER  VARCHAR2(30)    NOT NULL,
    ACCOUNT_HOLDER  VARCHAR2(20)    NOT NULL,
    IS_DEFAULT      NUMBER(1)       DEFAULT 0 NOT NULL,
    CREATED_AT      DATE            DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_BANK_ACCOUNT PRIMARY KEY (ACCOUNT_NO)
);
CREATE SEQUENCE BANK_ACCOUNT_SEQ START WITH 1 INCREMENT BY 1;

-- 2. POINT_WITHDRAW 테이블 (계좌 정보 포함, 관리자 처리 컬럼 추가)
CREATE TABLE POINT_WITHDRAW (
    WITHDRAW_NO      NUMBER          NOT NULL,
    MEMBER_NO        NUMBER          NOT NULL,
    AMOUNT           NUMBER          NOT NULL,
    BANK_NAME        VARCHAR2(30)    NOT NULL,
    ACCOUNT_NUMBER   VARCHAR2(30)    NOT NULL,
    ACCOUNT_HOLDER   VARCHAR2(20)    NOT NULL,
    STATUS           VARCHAR2(20)    DEFAULT '신청' NOT NULL,
    -- 신청 → 처리중 → 완료 | 거절
    ADMIN_NO         NUMBER          NULL,  -- 처리한 관리자 MEMBER_NO
    ADMIN_NICKNAME   VARCHAR2(15)    NULL,  -- 처리한 관리자 닉네임 (로그용)
    REJECT_REASON    VARCHAR2(200)   NULL,
    CREATED_AT       DATE            DEFAULT SYSDATE NOT NULL,
    PROCESSED_AT     DATE            NULL,
    CONSTRAINT PK_POINT_WITHDRAW PRIMARY KEY (WITHDRAW_NO)
);
CREATE SEQUENCE POINT_WITHDRAW_SEQ START WITH 1 INCREMENT BY 1;