-- 1. POINT_CHARGE에 MERCHANT_UID 컬럼 추가
ALTER TABLE POINT_CHARGE ADD MERCHANT_UID VARCHAR2(100);

-- 2. MERCHANT_UID 유니크 제약조건 추가
ALTER TABLE POINT_CHARGE
ADD CONSTRAINT UQ_MERCHANT_UID UNIQUE (MERCHANT_UID);

-- 3. BillingKey 테이블 신규 생성
CREATE TABLE BILLING_KEY (
    BILLING_KEY_NO NUMBER NOT NULL,
    MEMBER_NO NUMBER NOT NULL,
    CUSTOMER_UID VARCHAR2(100) NOT NULL,
    CARD_NAME VARCHAR2(50),
    CARD_NO VARCHAR2(20),
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_BILLING_KEY PRIMARY KEY (BILLING_KEY_NO),
    CONSTRAINT UQ_BILLING_KEY_MEMBER UNIQUE (MEMBER_NO)
);

-- 4. BillingKey 시퀀스 생성
CREATE SEQUENCE BILLING_KEY_SEQ START WITH 1 INCREMENT BY 1;