spring.application.name=project

# Oracle DB 연결
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@teacherdev09.kro.kr:8877:XE
spring.datasource.username=JAVAJAVA
spring.datasource.password=JAVAjava##0909

# JPA / Hibernate 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 스프링 부트 3.x (Hibernate 6) 용 Oracle 11g 완벽 호환 설정
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.dialect.version=11.2.0
